import { useState } from 'react';
import Layout from '../components/Layout';
import { Download, Mail, Printer, Eye, FileText, CheckCircle } from 'lucide-react';
import jsPDF from 'jspdf';
import './SharedPages.css';

function PurchaseOrderInvoice({ user, onLogout }) {
  const [orders, setOrders] = useState([
    {
      id: 'PO-2026-001',
      rfqId: 'RFQ-001',
      vendor: 'Global Suppliers',
      amount: 11800,
      tax: 1770,
      total: 13570,
      date: '2026-06-06',
      status: 'completed',
      items: [
        { product: 'Printer Paper A4', quantity: 100, unit: 'boxes', unitPrice: 42, total: 4200 },
        { product: 'Gel Pens', quantity: 500, unit: 'pieces', unitPrice: 15.2, total: 7600 }
      ],
      deliveryAddress: '123 Business Plaza, New York, NY 10001',
      invoiceGenerated: true
    },
    {
      id: 'PO-2026-002',
      rfqId: 'RFQ-002',
      vendor: 'Tech Solutions Inc',
      amount: 45000,
      tax: 6750,
      total: 51750,
      date: '2026-06-05',
      status: 'in_progress',
      items: [
        { product: 'Laptop Dell XPS 15', quantity: 20, unit: 'units', unitPrice: 2000, total: 40000 },
        { product: 'Wireless Mouse', quantity: 50, unit: 'pieces', unitPrice: 100, total: 5000 }
      ],
      deliveryAddress: '123 Business Plaza, New York, NY 10001',
      invoiceGenerated: false
    }
  ]);

  const [selectedOrder, setSelectedOrder] = useState(null);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailData, setEmailData] = useState({
    to: '',
    subject: '',
    message: ''
  });

  const generatePDF = (order) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text('VendorBridge', 20, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`${order.invoiceGenerated ? 'INVOICE' : 'PURCHASE ORDER'}`, 150, 20);
    
    // Order Details
    doc.setFontSize(10);
    doc.text(`${order.invoiceGenerated ? 'Invoice' : 'PO'} Number: ${order.id}`, 20, 35);
    doc.text(`Date: ${order.date}`, 20, 42);
    doc.text(`Status: ${order.status}`, 20, 49);
    
    // Vendor Info
    doc.setFontSize(12);
    doc.text('Vendor Details:', 20, 65);
    doc.setFontSize(10);
    doc.text(`Vendor: ${order.vendor}`, 20, 72);
    doc.text(`Delivery Address: ${order.deliveryAddress}`, 20, 79);
    
    // Items Table
    let yPos = 95;
    doc.setFontSize(12);
    doc.text('Items:', 20, yPos);
    yPos += 7;
    
    // Table Headers
    doc.setFillColor(37, 99, 235);
    doc.rect(20, yPos, 170, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('Product', 25, yPos + 5);
    doc.text('Qty', 100, yPos + 5);
    doc.text('Unit Price', 120, yPos + 5);
    doc.text('Total', 160, yPos + 5);
    yPos += 10;
    
    // Table Rows
    doc.setTextColor(0, 0, 0);
    order.items.forEach((item) => {
      doc.text(item.product, 25, yPos);
      doc.text(item.quantity.toString(), 100, yPos);
      doc.text(`$${item.unitPrice}`, 120, yPos);
      doc.text(`$${item.total}`, 160, yPos);
      yPos += 7;
    });
    
    // Totals
    yPos += 10;
    doc.text(`Subtotal: $${order.amount.toLocaleString()}`, 120, yPos);
    doc.text(`Tax (15%): $${order.tax.toLocaleString()}`, 120, yPos + 7);
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(`Total: $${order.total.toLocaleString()}`, 120, yPos + 14);
    
    // Footer
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by VendorBridge ERP System', 20, 280);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 285);
    
    return doc;
  };

  const handleDownloadPDF = (order) => {
    const doc = generatePDF(order);
    doc.save(`${order.id}.pdf`);
  };

  const handlePrint = (order) => {
    const doc = generatePDF(order);
    const pdfBlob = doc.output('blob');
    const url = URL.createObjectURL(pdfBlob);
    const printWindow = window.open(url);
    if (printWindow) {
      printWindow.onload = () => {
        printWindow.print();
      };
    }
  };

  const handleSendEmail = (order) => {
    setSelectedOrder(order);
    setEmailData({
      to: '',
      subject: `${order.invoiceGenerated ? 'Invoice' : 'Purchase Order'} ${order.id} from VendorBridge`,
      message: `Dear Vendor,\n\nPlease find attached ${order.invoiceGenerated ? 'invoice' : 'purchase order'} ${order.id} for your review.\n\nOrder Total: $${order.total.toLocaleString()}\n\nBest regards,\nVendorBridge Team`
    });
    setShowEmailModal(true);
  };

  const handleEmailSubmit = (e) => {
    e.preventDefault();
    alert(`Email sent successfully to ${emailData.to}!\n\n${selectedOrder.id} has been delivered.`);
    setShowEmailModal(false);
  };

  const handleGenerateInvoice = (orderId) => {
    setOrders(orders.map(order => 
      order.id === orderId ? { ...order, invoiceGenerated: true } : order
    ));
    alert(`Invoice generated for ${orderId}!`);
  };

  return (
    <Layout user={user} onLogout={onLogout}>
      <div className="purchase-orders">
        <div className="page-header">
          <div>
            <h1>Purchase Orders & Invoices</h1>
            <p>Manage procurement documents</p>
          </div>
        </div>

        <div className="orders-list">
          {orders.map((order) => (
            <div key={order.id} className="order-card card">
              <div className="order-header">
                <div>
                  <h3>{order.id}</h3>
                  <p className="order-vendor">{order.vendor}</p>
                </div>
                <div className="badges">
                  <span className={`badge badge-${order.status === 'completed' ? 'success' : 'primary'}`}>
                    {order.status.replace('_', ' ')}
                  </span>
                  {order.invoiceGenerated && (
                    <span className="badge badge-info">Invoice Generated</span>
                  )}
                </div>
              </div>

              <div className="order-details-grid">
                <div className="detail-col">
                  <span className="label">RFQ Reference</span>
                  <p>{order.rfqId}</p>
                </div>
                <div className="detail-col">
                  <span className="label">Date</span>
                  <p>{order.date}</p>
                </div>
                <div className="detail-col">
                  <span className="label">Subtotal</span>
                  <p>${order.amount.toLocaleString()}</p>
                </div>
                <div className="detail-col">
                  <span className="label">Tax (15%)</span>
                  <p>${order.tax.toLocaleString()}</p>
                </div>
                <div className="detail-col">
                  <span className="label">Total Amount</span>
                  <p className="amount">${order.total.toLocaleString()}</p>
                </div>
              </div>

              <div className="order-items">
                <h4>Items ({order.items.length})</h4>
                <div className="items-summary">
                  {order.items.map((item, idx) => (
                    <div key={idx} className="item-summary">
                      <span>{item.product}</span>
                      <span>{item.quantity} {item.unit} × ${item.unitPrice}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="order-actions">
                <button className="btn btn-sm btn-outline" onClick={() => setSelectedOrder(order)}>
                  <Eye size={16} />
                  View Details
                </button>
                
                {!order.invoiceGenerated && (
                  <button className="btn btn-sm btn-secondary" onClick={() => handleGenerateInvoice(order.id)}>
                    <FileText size={16} />
                    Generate Invoice
                  </button>
                )}
                
                <button className="btn btn-sm btn-outline" onClick={() => handleDownloadPDF(order)}>
                  <Download size={16} />
                  Download PDF
                </button>
                
                <button className="btn btn-sm btn-outline" onClick={() => handlePrint(order)}>
                  <Printer size={16} />
                  Print
                </button>
                
                <button className="btn btn-sm btn-primary" onClick={() => handleSendEmail(order)}>
                  <Mail size={16} />
                  Send Email
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Order Details Modal */}
        {selectedOrder && !showEmailModal && (
          <div className="modal-overlay" onClick={() => setSelectedOrder(null)}>
            <div className="modal large-modal" onClick={(e) => e.stopPropagation()}>
              <div className="modal-header">
                <h2>{selectedOrder.id} Details</h2>
                <button className="icon-btn" onClick={() => setSelectedOrder(null)}>×</button>
              </div>
              <div className="modal-body">
                <div className="invoice-preview">
                  <div className="invoice-header">
                    <div>
                      <h1>VendorBridge</h1>
                      <p>Procurement & Vendor Management</p>
                    </div>
                    <div>
                      <h2>{selectedOrder.invoiceGenerated ? 'INVOICE' : 'PURCHASE ORDER'}</h2>
                      <p>{selectedOrder.id}</p>
                    </div>
                  </div>

                  <div className="invoice-section">
                    <div>
                      <h3>Vendor Details</h3>
                      <p><strong>{selectedOrder.vendor}</strong></p>
                      <p>{selectedOrder.deliveryAddress}</p>
                    </div>
                    <div>
                      <h3>Order Information</h3>
                      <p>Date: {selectedOrder.date}</p>
                      <p>Status: {selectedOrder.status}</p>
                      <p>RFQ: {selectedOrder.rfqId}</p>
                    </div>
                  </div>

                  <table className="invoice-table">
                    <thead>
                      <tr>
                        <th>Product/Service</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      {selectedOrder.items.map((item, idx) => (
                        <tr key={idx}>
                          <td>{item.product}</td>
                          <td>{item.quantity} {item.unit}</td>
                          <td>${item.unitPrice}</td>
                          <td>${item.total}</td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot>
                      <tr>
                        <td colSpan="3"><strong>Subtotal</strong></td>
                        <td><strong>${selectedOrder.amount.toLocaleString()}</strong></td>
                      </tr>
                      <tr>
                        <td colSpan="3"><strong>Tax (15%)</strong></td>
                        <td><strong>${selectedOrder.tax.toLocaleString()}</strong></td>
                      </tr>
                      <tr className="total-row">
                        <td colSpan="3"><strong>Total Amount</strong></td>
                        <td><strong>${selectedOrder.total.toLocaleString()}</strong></td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Email Modal */}
        {showEmailModal && (
          <div className="modal-overlay" onClick={() => setShowEmailModal(false)}>
            <div className="modal" onClick={(e) => e.stopPropagation()}>
              <div className="modal-header">
                <h2>Send via Email</h2>
                <button className="icon-btn" onClick={() => setShowEmailModal(false)}>×</button>
              </div>
              <form onSubmit={handleEmailSubmit}>
                <div className="modal-body">
                  <div className="form-group">
                    <label>To *</label>
                    <input
                      type="email"
                      className="form-control"
                      placeholder="vendor@example.com"
                      value={emailData.to}
                      onChange={(e) => setEmailData({ ...emailData, to: e.target.value })}
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label>Subject *</label>
                    <input
                      type="text"
                      className="form-control"
                      value={emailData.subject}
                      onChange={(e) => setEmailData({ ...emailData, subject: e.target.value })}
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label>Message *</label>
                    <textarea
                      className="form-control"
                      value={emailData.message}
                      onChange={(e) => setEmailData({ ...emailData, message: e.target.value })}
                      rows="6"
                      required
                    />
                  </div>
                  <div className="alert alert-info">
                    <FileText size={18} />
                    <span>PDF document will be attached automatically</span>
                  </div>
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-outline" onClick={() => setShowEmailModal(false)}>
                    Cancel
                  </button>
                  <button type="submit" className="btn btn-primary">
                    <Mail size={18} />
                    Send Email
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}

export default PurchaseOrderInvoice;
